controllers:
    resource: ../src/Controller/
    type: attribute
api_top_authors:
    path: '/api/top-authors'
    controller: 'App\Controller\ApiArticleController::getTopAuthors'
    methods: GET
api_author_articles:
    path: '/api/author/{id}/articles'
    controller: 'App\Controller\ApiArticleController::getAuthorArticles'
    methods: GET
api_get_article:
    path: '/api/article/{id}'
    controller: 'App\Controller\ApiArticleController::getArticle'
    methods: GET
api_add_article:
    path: '/api/article/add'
    controller: 'App\Controller\ApiArticleController::addArticle'
    methods: POST
api_edit_article:
    path: '/api/article/{id}/edit'
    controller: 'App\Controller\ApiArticleController::editArticle'
    methods: PATCH
add_article:
    path: '/article/add'
    controller: 'App\Controller\ArticleController::addArticle'
edit_article:
    path: '/article/{id}/edit'
    controller: 'App\Controller\ArticleController::editArticle'
view_article:
    path: '/article/{id}'
    controller: 'App\Controller\ArticleController::viewArticle'
view_top_authors:
    path: '/top-authors'
    controller: 'App\Controller\ArticleController::viewTopAuthors'
index:
    path: '/'
    controller: 'App\Controller\ArticleController::index'